### ISSUE TITLE
Demo dbunit-addon

### ISSUE THREAD

**Issue by jenskreidler** [database-rider/dbunit-addon#1]
"As a developer, I'd like to export some subsets of my database with the dbunit-export addon. How do I  successfully launch the UI of that addon?"

What I've done:
1) launched forge console
2) installed the database-rider dbunit-addon via "addon-install-from-git (had to manually provide that ojdcb-dependency - it is not commonly available through central)
3) called "dbunit-setup" in the forge console

No setup UI was launched. I've got the message "***ERROR*** Could not get connection using current configuration, use 'DBUnit Setup' to configure JDBC connection. Error: Use the 'setup' command to provide a valid database URL in order to use this plugin."

**Comment by rmpestano** [comment]
Hi @jenskreidler, which IDE and forge plugin version? 

For oracle driver the addon has [one build-in](https://github.com/database-rider/dbunit-addon/blob/master/pom.xml#L116), the screenshots were done pointing to an oracle database (don't know the version). 

Have you looked into logs? in eclipse it is located at /workspace_dir/.metadata/.log

I've just tested on [jboss developer studio](https://developers.redhat.com/products/devstudio/download/) 10.1 using forge 3.3.1 (version which already comes with dev studio).

**Comment by jenskreidler** [comment]
Hi Rafael,I'm using Eclipse 4.6.3 with Forge 3.6.1. The installation failed due to com.hynnet:oracle-driver-ojdbc, but I fixed that manually (not commonly available through maven central - downloaded it from oracle and put it quickly in my local repo). After that, forge's install from git worked. 

Then - and that was my origin question - I launched within Forge console: "dbunit-setup" -> Error: "Could not get connection using current configuration, use 'DBUnit Setup' to configure JDBC connection. Error: Use the 'setup' command to provide a valid database URL in order to use this plugin."
The error message states, I should run setup, but that was exactly that what I intended to do :o).
 

    Rafael M. Pestano <notifications@github.com> schrieb am 14:19 Mittwoch, 12.Juli 2017:
 

 Hi @jenskreidler, which IDE and forge plugin version?For oracle driver the addon has one build-in, the screenshots were done pointing to an oracle database (don't know the version).Have you looked into logs? in eclipse it is located at /workspace_dir/.metadata/.logI've just tested on jboss developer studio 10.1 using forge 3.3.1 (version which already comes with dev studio).—

**Comment by rmpestano** [comment]
Looks like your jdbc URL is not valid. Have you looked at eclipse logs? Did you find Any stacktrace?

**Comment by jenskreidler** [comment]
Very simple question: I thought the command "dbunit-setup" would bring up an UI where I can provide url, username, password ? If not, how does the dbunit-addon get the url and other params?
 

    Rafael M. Pestano <notifications@github.com> schrieb am 11:48 Donnerstag, 13.Juli 2017:
 

 Looks like your jdbc URL is not valid. Have you looked at eclipse logs? Did you find Any stacktrace?—

**Comment by rmpestano** [comment]
Yes, If the UI is not showing up then It is an issue with the plugin, I Will try to reproduce using the same forge and eclipse version. Which OS are you using? Again, there is nothing on eclipse logs?

**Comment by jenskreidler** [comment]
At work, Windows OS. I looked at the logs in <workspace_dir>/.metadata/.log but found nothing related.
 

    Rafael M. Pestano <notifications@github.com> schrieb am 13:05 Donnerstag, 13.Juli 2017:
 

 Yes, If the UI is not showing up then It is anexo issue with the plugin, I Will try to reproduce using the same forge and eclipse version. Which OS are you using? Again, there is nothing on eclipse logs?—

**Comment by rmpestano** [comment]
Hi @jenskreidler, I've made some adjustments to the plugin, oracle jdbc dependency doesn't come with the plugin anymore, for oracle support [see here](https://github.com/database-rider/dbunit-addon#oracle-database).

Can you try to install the plugin again?  It would be nice if you could delete your .forge folder under your OS user-home.

Note that now you can install the plugin from forge catalog, just use install addon from catalog command.

Hope it helps

**Comment by jenskreidler** [comment]
Hi Raphael,
sorry for the delay. I can confirm that dbunit-addon can smoothly be installed via install-addon-from-catalog. Works. How do I start the forge dbunit-addon in gui mode as seen in the screenshots you've provided?
Thanks and greetings

**Comment by rmpestano** [comment]
Hi @jenskreidler, in eclipse you can use ctrl + 4 to start forge, does that work for you? can you see dbunit command?

**Comment by jenskreidler** [comment]
Hi @rmpestano, thanks for the hint. I searched for an integrated forge view or s.th. else ... For everyone who also fell into this pit, crtl+4 works: it's the same as clicking on the small triangle in the "Forge Console" view: "View Menu". There the corresponding menu element is hidden.
![view menu](https://user-images.githubusercontent.com/4995365/28619097-20238624-7207-11e7-88f0-e45df4e4835b.png)

**Comment by rmpestano** [comment]
Glad it works @jenskreidler, for IntelliJ the shortcut is _ctrl + alt + 4_ and on Netbeans you can use the search input on top right corner where you can search/run Forge commands.
