### ISSUE TITLE
Postgresql driver

### ISSUE THREAD

**Issue by kdurnoga** [database-rider/dbunit-addon#2]
Does the addon come with a bundled Postgresql JDBC driver? I'm getting the following error when I run the addon:
```
***ERROR*** Could not get connection using current configuration, use 'DBUnit Setup' to configure JDBC connection. Error: No suitable driver found for jdbc:postgresql://localhost:5432
```

**Comment by rmpestano** [comment]
Hi, yes It comes with [this one](https://github.com/database-rider/dbunit-addon/blob/8616125030e998664804c85549d47e33b71a6d05/pom.xml#L101) but If Its not working you can put one (which already works with your database) into the plugin directory as is done with Oracle db, [see here](https://github.com/database-rider/dbunit-addon/blob/master/README.asciidoc#oracle-database)

**Comment by kdurnoga** [comment]
Ok, thanks.
